### ISSUE TITLE
Zoom can not work in Firefox 69.0b4 (64-bit) Add-on

### ISSUE THREAD

**Issue by jhrxx** [dimsemenov/PhotoSwipe#1634]
Winows 10 Firefox 69.0b4 (64-bit)

When I add PhotoSwipe to my add-on by create a demo slider as the [getting-started](https://photoswipe.com/documentation/getting-started.html)
then click zoom button get following error(pause on exceptions is enable).

> TypeError: 'requestAnimationFrame' called on an object that does not implement interface Window.

modify the code can fix it

photoswipe.js:155
`if(window.requestAnimationFrame) {`
`	features.raf = window.requestAnimationFrame.bind(window);`
`	features.caf = window.cancelAnimationFrame.bind(window);`
`}`

Ref: [stackoverflow](https://stackoverflow.com/questions/9677985/uncaught-typeerror-illegal-invocation-in-chrome)
