### ISSUE TITLE
PhotoSwipe Default UI 4.1.2 - Dragging outside the window causes multiple errors

### ISSUE THREAD

**Issue by DanRobinsonRV** [dimsemenov/PhotoSwipe#1393]
I've found that the following steps seem to cause a lot of errors in PhotoSwipe:

- Click a slide, and drag it to one side
- Keep dragging until the mouse cursor leaves the window (either outside the browser window itself, or outside an iframe containing the gallery)
- Release the mouse button while still outside the window

This causes a few errors to pop up:

`TypeError: t.getAttribute is not a function (photoswipe-ui-default.js:578:5)`

The gallery acts as though the drag was never released. I know it's not an issue with my configuration, as it happens on the documentation example too:

http://photoswipe.com/documentation/getting-started.html

I noticed that the gallery on the [main page of your site](http://photoswipe.com/) doesn't seem to have the issue, so I downgraded to that version of PhotoSwipe Default UI (4.1.0) and the issue is no longer occuring, so this must be an issue introduced in a later version of PhotoSwipe Default UI.

Hope this helps.

**Comment by shobee** [comment]
@dimsemenov Same here. Reproducible on Win 7 / FF 54. With MacOS 10.12.3 / Chrome 59.0.3071.115 it's working fine.

**Comment by shobee** [comment]
Seems like that bug was introduced with https://github.com/dimsemenov/PhotoSwipe/commit/3fa508e743d01c288ca94be9ca13f66347da2adc#diff-1ac5fbd2e237d8e0d36283b1536af7e8. At least if I change all occurences of `getAttribute('class')` back to `className` the bug disappears. Of course this is no solution since obviously these changes were made to fix another bug. No idea how to solve this.

**Comment by BARNZ** [comment]
Related #1371
